name: Test CI

on:
  push:
    branches:
      - develop

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Test core
        run: yarn run test-core
      - name: Test web
        run: yarn run test-web
